freelencia/urls.py
from django.contrib import admin
from django.urls import path


from django.urls import re_path, include
from hub import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    re_path(r'hub/', include('hub.urls')),

    re_path(r'^$', views.index, name='index'),
    
    re_path(r'^special/', views.special, name='special'),
    
    re_path(r'^logout/$', views.user_logout, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hub/urls.py
from django.urls import re_path
from . import views

app_name = 'hub'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    
    re_path(r'^user_login/$', views.user_login, name='user_login'),
    
    re_path(r'^become-freelancer/$', views.become_freelancer, name='become_freelancer'),
    
    re_path(r'^dashboard/$', views.freelancer_dashboard, name='freelancer_dashboard'),
    
    re_path(r'^freelancer-dashboard/$', views.freelancer_dashboard, name='freelancer_dashboard'),
    
    re_path(r'^programming/$', views.show_programming, name='cat_programming'),
    
    re_path(r'^graphics/$', views.show_graphics, name='cat_graphics'),
    
    re_path(r'^video/$', views.show_video, name='cat_video'),
    
    re_path(r'^business/$', views.show_business, name='cat_business'),

    re_path(r'^freelancer/hire/(?P<freelancer_id>\d+)/$', views.hire_freelancer, name='hire_freelancer'),
    
    re_path(r'^freelancer/view/(?P<freelancer_id>\d+)/$', views.view_freelancer, name='view_freelancer'),

    re_path(r'^freelancer/request/(?P<request_id>\d+)/$', views.view_request, name='view_request'),
    
    re_path(r'^freelancer/job/(?P<request_id>\d+)/finish/$', views.finish_job, name='finish_job'),
    
    re_path(r'^freelancer/job/(?P<request_id>\d+)/cancel/$', views.cancel_job, name='cancel_job'),

    re_path(r'^freelancer/request/(?P<request_id>\d+)/accept/$', views.accept_request, name='accept_request'),
    
    re_path(r'^freelancer/request/(?P<request_id>\d+)/decline/$', views.decline_request, name='decline_request'),

    re_path(r'^hired-freelancers/', views.hired_freelancers, name='hired_freelancers'),
    
    re_path(r'^hired-freelancer/(?P<freelancer_id>\d+)/$', views.hired_freelancer_profile, name='hired_freelancer_profile'),

    re_path(r'^freelancer/request/(?P<request_id>\d+)/', views.view_client_request, name='view_client_request'),
    
    re_path(r'^freelancer/hired/(?P<request_id>\d+)/', views.view_hired_client, name='view_hired_client'),
]

shastafiverr/freelancer/urls.py
from freelancer import views
from django.urls import re_path
from django.urls import path
from . import views
app_name = 'freelancer'

urlpatterns = [
	re_path(r'/register/', views.register, name='register'),

	re_path(r'/user_login/', views.user_login, name='user_login'),
    
    re_path(r'/become-freelancer/', views.become_freelancer, name='become_freelancer'),
    
	path("/dashboard/", views.freelancer_dashboard, name="freelancer_dashboard"),

]

shastafiverr/freelancer/views.py
from django.shortcuts import redirect, render
from .forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, 'freelancer/index.html')

@login_required
def special(request):
    return HttpResponse("You are now logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.role = 'customer'
            if 'profile_pic' in request.FILES:
                print('Got it...')
                profile.profile_pic = request.FILES['profile_pic']
            else:
                pass
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'freelancer/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active: 
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Sorry, your account is inactive.")
        else:
            return render(request, 'freelancer/login.html', {
                'error': "Invalid username or password."
            })
    else:
        return render(request, 'freelancer/login.html', {})

# Not tested or fixed yet.
@login_required
def become_freelancer(request):
    profile = request.user.userprofileinfo
    profile.role = 'freelancer'
    profile.save()
    return redirect('freelancer:freelancer_dashboard')

def freelancer_dashboard(request):
    return render(request, 'freelancer/freelancer_dashboard.html')

shastafiverr/templates/freelancer/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>ShastaaFiverr</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                
                      <div class="navbar-header">
                            <a class="navbar-brand" style="color: rgb(66, 250, 130);" href="{% url 'index' %}">
                                <strong>ShastaaFiverr</strong>
                            </a>
                            <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
                       </div>

                    <div class="row" style="display:flex; justify-content:flex-end; align-items:center;">
                        
                    
                        {% if user.is_authenticated %}
                            <span class="navbar-text" style="color:white; margin-right:10px;">Signed in as {{ user.username }}</span>
                            <a class="btn btn-danger navbar-btn" href="{% url 'logout' %}" >Logout</a>
                        {% else %}
                            <a class="btn btn-primary navbar-btn" href="{% url 'freelancer:user_login' %}">Login</a>
                            <a class="btn btn-success navbar-btn" href="{% url 'freelancer:register' %}">Register</a>
                        
                        {% endif %}
                        
                    </div>
                    
                <div class="row" style="padding: 5px 0; display:flex; justify-content:space-between; align-items:center;">
                        <ul class="nav navbar-nav">
                            <li><a class="navbar-brand"  href="#">Programming and Tech</a></li>
                            <li><a class="navbar-brand"  href="#">Graphics and Design</a></li>
                            <li><a class="navbar-brand"  href="#">Video and Animation</a></li>
                            <li><a class="navbar-brand"  href="#">Business</a></li>
                            
                        </ul>  
                    
                    <div class="row" style="display:flex; justify-content:flex-end; align-items:center;">

                        {% if user.is_authenticated %}
                            {% if user.userprofileinfo.role == "freelancer" %}
                                <a class="btn btn-primary navbar-btn" href="{% url 'freelancer:freelancer_dashboard' %}">Dashboard</a>
                            {% elif user.userprofileinfo.role == "customer" %}
                                <a class="btn btn-success navbar-btn" href="{% url 'freelancer:become_freelancer' %}">Become A Freelancer</a>
                            {% endif %}
                        {% endif %}

                    </div>
                </div>

            </div >
        </nav>
        <div class="container">
            {% block body_block %}


            {% endblock %}
        </div>
    </body>
</html>

shastafiverr/templates/freelancer/freelancer_dashboard.html
{% extends "freelancer/base.html" %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Welcome To <strong>ShastaaFiverr!</strong></h2>
        {% if user.is_authenticated %}
            <h3>Assalamualaikum {{user.username}}! You are now a freelancer!</h3>
            <br>
            <h3><strong>This Project is the joint creation of:</strong></h4>
            <h4>Areez Ahasan Rayat</h4>
            <h4>Mohammed Abdullah</h4>
            <h4>Shah Amir Solaiman</h4>
            <h4>Sumaiya Akter Suma</h4>

        {% else %}
            <h2>Please Login or Register in order to access this site.</h2>
        {% endif %}
    </div>
</div>

{% endblock %}

shastafiverr/templates/freelancer/index.html
{% extends "freelancer/base.html" %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Welcome To <strong>ShastaaFiverr!</strong></h2>
        {% if user.is_authenticated %}
            <h3>Assalamualaikum {{user.username}}!</h3>
            <br>
            <h3><strong>This Project is the joint creation of:</strong></h4>
            <h4>Areez Ahasan Rayat</h4>
            <h4>Mohammed Abdullah</h4>
            <h4>Shah Amir Solaiman</h4>
            <h4>Sumaiya Akter Suma</h4>

        {% else %}
            <h2>Please Login or Register in order to access this site.</h2>
        {% endif %}
    </div>
</div>

{% endblock %}

shastafiverr/templates/freelancer/login.html
{% extends "freelancer/base.html" %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Please Login Here</h2>
        <form method="post" action="{% url 'freelancer:user_login' %}">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="text" name="password" placeholder="Enter Password">

            <input type="submit" name="savebutton" value="Enter">

        </form>

    </div>
</div>

{% endblock %}

shastafiverr/templates/freelancer/registration.html
{% extends "freelancer/base.html" %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        {% if registered %}
            <h2>Thanks for Registering, Please login.</h2>
        {% else %}
            <h2>Please Fill up the provided form to Register</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" name="userregistration" value="Register" >
            </form>
        {% endif %}
    </div>
</div>

{% endblock %}